
node {
notify('Started')
try {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

  stage('GitCheckOut') {
  git branch: 'production', url: 'https://github.com/komali100/capstone-devops.git'
}
stage('Build Managment') {
      def downloadSpec = """{
	 "files": [
	{
	"pattern": "petclinic-war/*.war",
	"target": "roles/petclinic/files/"
        }
	]
	}"""
	server.download spec: downloadSpec
 }

stage('Getting Ready for Ansible Deploy'){
   sh "echo \'<h1> TASK BUILD ID: ${env.BUILD_DISPLAY_NAME}</h1>\'  > roles/petclinic/files/jenkins.html"
  }

stage('Deployment - Production'){
   sh 'ansible-playbook petclinic.yaml'
  }
  notify('Completed')

} catch(err){
  notify("Error ${err}")
  currentBuild.result = 'FAILURE'
 }
}

def notify(status){
    emailext(
    to: "komali.arepalli2@mindtree.com",
    subject: "${status} :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
    body:"""<p>${status}: :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
            <p>Check Console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}

