node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

  stage('GitCheckOut') {
  git branch: 'production', url: 'https://github.com/komali100/capstone-devops.git'
}


stage('Getting Ready for Ansible Deploy'){
   sh "echo \'<h1> TASK BUILD ID: ${env.BUILD_DISPLAY_NAME}</h1>\'  > roles/petclinic/files/jenkins.html"
  }

stage('Deployment - Production'){
   sh 'ansible-playbook petclinic.yaml'
  }
}
