
node {
    stage('GitCheckOut') {
  git branch: 'main', url: 'https://github.com/komali100/capstone-devops.git'
}
def project_path= "01-jenkins/petclinic-code"
dir(project_path){
stage('maven clean') {
  sh '''mvn clean''' 
}
stage('maven compile') {
  sh '''mvn compile'''
}
stage('maven test') {
  sh '''mvn test'''
}
stage('maven pkg') {
  sh '''mvn package'''
}
  stage('Archive Artifacts') {
  archive 'target/*.war'
  }

stage('Deployment - PreProd'){
sh 'docker-compose up -d --build'
}
} 
stage('Deployment - stage'){
   deploy adapters: [tomcat8(credentialsId: '02', path: '', url: 'http://oysup74925dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: '01-jenkins/petclinic-code/target/petclinic.war'
}

