---

- hosts: localhost
  connection: local
  name: WebServer setup
  become: yes
  tasks:
  - name: Installing Apache2 Packages
    apt: name=apache2 state=present

  - name: Start Apache2 service
    service: name=apache2 state=started

  - name: Deploy Custom web page
    copy: src=files/index.html dest=/var/www/html/
