node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

// Project Dir
    def project_path ="Download"

  stage('GitCheckOut') {
  git branch: 'stage', url: 'https://github.com/komali100/capstone-devops.git'
}

dir(project_path){
stage('Build Managment') {
      def downloadSpec = """{
	 "files": [
	{
	"pattern": "petclinic-war/*.war",
	"target": "files"
        }
	]
	}"""
	server.download spec: downloadSpec
 }


stage('Deployment - Stage'){
   deploy adapters: [tomcat8(credentialsId: '02', path: '', url: 'http://oysup74925dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: 'files/petclinic.war'
}

}}
